# Default values for techtalk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

techTalksProducer:
  replicas: 3
  image:
    repository: nileshgule/techtalksproducer
    tag: go
  containerPort: 8080
  labels:
    run: rabbitmq-producer
    app: techtalks
    backstage.io/kubernetes-id: techtalks-producer-api
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080

techTalksConsumer:
  labels:
    run: rabbitmq-consumer
    app: techtalks
    backstage.io/kubernetes-id: techtalks-consumer-api
  image:
    repository: "nileshgule/techtalksconsumer"
    tag: go
  containerPort: 8081