apiVersion: apps/v1
kind: Deployment

metadata:
  name: rabbitmq-consumer-deployment
  
  labels:
    {{- include "techtalks.consumerLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rabbitmq-consumer

  template:
    metadata:
      labels:
        {{- include "techtalks.consumerLabels" . | nindent 8 }}
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "techtalks-consumer"
        dapr.io/app-port: "{{ .Values.techTalksConsumer.containerPort }}"
                        
    spec:
      containers:
        - name: rabbitmq-consumer
          # image: ngacrregistry.azurecr.io/techtalksconsumer:java
          image: {{ .Values.techTalksConsumer.image.repository}}:{{ .Values.techTalksConsumer.image.tag }}
          ports:
            - containerPort: {{ .Values.techTalksConsumer.containerPort }}
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
