apiVersion: apps/v1
kind: Deployment

metadata:
  name: rabbitmq-producer-deployment
  labels:
    run: rabbitmq-producer
    app: techtalks

spec:
  replicas: 3
  selector:
    matchLabels:
      run: rabbitmq-producer

  template:
    metadata:
      labels:
        run: rabbitmq-producer
        app: techtalks
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "rabbitmq-producer"
        dapr.io/app-port: "8080"
        # dapr.io/config: "zipkin"
    spec:
      containers:
        - name: techtalksproducer
          # image: ngacrregistry.azurecr.io/techtalksproducer:dotnet
          # image: ngacrregistry.azurecr.io/techtalksproducer:go
          # image: ngacrregistry.azurecr.io/techtalksproducer:java
          # image: nileshgule/techtalksproducer:dotnet
          image: nileshgule/techtalksproducer:java
          # image: nileshgule/techtalksproducer:go
          
          # env:
          #   - name: ASPNETCORE_ENVIRONMENT
          #     value: Development
          ports:
            - containerPort: 8080
              # protocol: TCP
          resources:
            requests:
              cpu: "10m" #1% of a core
              memory: "200Mi"
            limits:
              cpu: "50m" #5% of a core
              memory: "500Mi"
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
