apiVersion: apps/v1
kind: Deployment

metadata:
  name: rabbitmq-producer-deployment
  labels:
    run: rabbitmq-producer
    app: techtalks

spec:
  replicas: 2
  selector:
    matchLabels:
      run: rabbitmq-producer

  template:
    metadata:
      labels:
        run: rabbitmq-producer
        app: techtalks
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "rabbitmq-producer"
        dapr.io/app-port: "80"
        # dapr.io/app-port: "8080"
        # dapr.io/config: "zipkin"
        # dapr.io/sidecar-liveness-probe-delay-seconds: "60"
    spec:
      containers:
        - name: techtalksproducer
          image: ngacrregistry.azurecr.io/techtalksproducer:dotnet
          # image: ngacrregistry.azurecr.io/techtalksproducer:java
          
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          ports:
            # - containerPort: 8080
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: "10m" #1% of a core
              memory: "200Mi"
            limits:
              cpu: "50m" #5% of a core
              memory: "500Mi"
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
