version: "3"

services:
  techtalks.producer:
    image: techtalksproducer:dotnet
    build:
      context: src/dotnet
      dockerfile: Dockerfile-V3-TechTalksProducer

  techtalks.consumer:
    image: techtalksconsumer:dotnet
    build:
      context: src/dotnet
      dockerfile: Dockerfile-TechTalksConsumer
