version: "3"

services:
  techtalks.producer:
    image: ngacrregistry.azurecr.io/techtalksproducer:dotnet
    build:
      context: src/dotnet
      dockerfile: Dockerfile-TechTalksMQProducer

  techtalks.consumer:
    image: ngacrregistry.azurecr.io/techtalksconsumer:dotnet
    build:
      context: src/dotnet
      dockerfile: Dockerfile-TechTalksConsumer
