version: "3"

services:
  techtalks.producer:
    image: nileshgule/techtalksproducer:dotnet
    build:
      context: src/dotnet
      dockerfile: Dockerfile-v3-TechTalksProducer

  techtalks.consumer:
    image: nileshgule/techtalksconsumer:dotnet
    build:
      context: src/dotnet
      dockerfile: Dockerfile-TechTalksConsumer
