# http://localhost:8081/api/TechTalks/?numberOfMessages=500

# http://20.197.107.149/generate/?numberOfTalks=5000

# second request

# http://20.212.95.39:8080/generate/10000


# http://localhost:8080/generate/1000


http://40.119.229.178/producer/generate/1000


