# # FROM openjdk:19-jdk as build

# FROM maven:3.8-jdk-11

# WORKDIR /app

# COPY . /techtalks-Producer/

# WORKDIR /techtalks-Producer

# # RUN mvn --version

# RUN mvn clean package

# FROM openjdk:19-jdk-slim
# COPY --from=build /techtalks-Producer/target/*.jar TechTalksProducer.jar
# EXPOSE 80
# ENTRYPOINT ["java", "-jar", "TechTalksProducer.jar"]

FROM openjdk:19-alpine AS build

# Set the working directory
WORKDIR /app

# Copy the Maven dependencies
COPY pom.xml /app/pom.xml
COPY mvnw /app/mvnw
COPY .mvn /app/.mvn

# # Build the application
# RUN ./mvnw package -DskipTests

RUN ./mvnw dependency:go-offline

# Copy the application files
COPY src /app/src

# Build the application
RUN ./mvnw package -DskipTests

# Create the runtime image
FROM openjdk:19-alpine

# Set the working directory
WORKDIR /app

# Copy the application files
COPY --from=build /app/target/techtalks-producer-0.0.1-SNAPSHOT.jar TechTalksProducer.jar

# Expose the application port
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "TechTalksProducer.jar"]

