FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine AS build-env

WORKDIR /app

COPY producer /producer/
COPY TechTalksModel /TechTalksModel/

WORKDIR /producer
RUN dotnet restore

RUN dotnet publish --configuration Release --output releaseOutput --no-restore

#build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0-alpine

WORKDIR /producer

COPY --from=build-env /producer/releaseOutput ./

ENTRYPOINT ["dotnet", "producer.dll"]
