FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine AS build-env

WORKDIR /app

COPY consumer /consumer/
COPY TechTalksModel /TechTalksModel/

WORKDIR /consumer
# RUN dotnet restore

RUN --mount=type=cache,id=nuget,target=/root/.nuget/packages dotnet restore

RUN --mount=type=cache,id=nuget,target=/root/.nuget/packages dotnet publish --configuration Release --output releaseOutput --no-restore

#build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0-alpine

WORKDIR /consumer

COPY --from=build-env /consumer/releaseOutput ./

ENTRYPOINT ["dotnet", "consumer.dll"]
