FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env

WORKDIR /app

COPY producer /producer/
COPY TechTalksModel /TechTalksModel/

WORKDIR /producer
RUN dotnet restore

RUN dotnet publish --configuration Release --output releaseOutput --no-restore

#build runtime image with Ubuntu Linux
FROM mcr.microsoft.com/dotnet/aspnet:7.0-jammy

WORKDIR /producer

COPY --from=build-env /producer/releaseOutput ./

ENTRYPOINT ["dotnet", "producer.dll"]
