FROM eclipse-temurin:19.0.1_10-jdk-alpine as build

WORKDIR /app

COPY techtalks-producer /techtalks-Producer/

WORKDIR /techtalks-Producer

RUN mvn clean package

FROM eclipse-temurin:19-jre-alpine
COPY --from=build /techtalks-producer/target/techtalks-producer-0.0.1-SNAPSHOT.jar TechTalksProducer.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "TechTalksProducer.jar"]
