FROM eclipse-temurin:19.0.1_10-jdk-alpine as build

WORKDIR /app

COPY techtalks-consumer /techtalks-consumer/

WORKDIR /techtalks-consumer

RUN mvn clean package

FROM eclipse-temurin:19-jre-alpine
COPY --from=build /techtalks-consumer/target/*.jar TechTalksConsumer.jar
EXPOSE 80
ENTRYPOINT ["java", "-jar", "TechTalksConsumer.jar"]
