apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq-pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    # value: "amqp://guest:guest@localhost:5672/"
    secretKeyRef:
      name: rabbitmq-secret
      key: host
  - name: durable
    value: true
  - name: deletedWhenUnused
    value: false
  - name: autoAck
    value: false
  - name: prefetchCount
    value: 50
  - name: reconnectWait
    value: 0
  - name: concurrencyMode
    value: single  
  - name: exchangeKind
    value: fanout
  