apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq-secret
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: "../../../Components//local/secretsfile.json"
  - name: nestedSeparator
    value: ":"
  - name: multiValued
    value: "false"
