apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
data:
  host: YW1xcDovL3VzZXI6UEFTU1dPUkRAcmFiYml0bXEuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDo1Njcy
  # host: 'amqp://user:PASSWORD@rabbitmq.default.svc.cluster.local:5672/rabbitmq'
  # host: 'amqp://user:PASSWORD@rabbitmq.default.svc.cluster.local:5672/'
  # host: 'amqp://user:tCUN6UizuwTZ@20.212.110.83:5672/'