apiVersion: v1
kind: Service

metadata:
  name: rabbitmq-producer-service
  labels:
    {{- include "techtalks.producerLabels" . | nindent 4 }}
  annotations:
    dapr.io/enabled: "true"
    dapr.io/app-id: "rabbitmq-producer-service"
    dapr.io/app-port: "{{ .Values.techTalksProducer.service.port}}"
    dapr.io/config: "zipkin"
spec:
  # type: LoadBalancer
  type: {{ .Values.techTalksProducer.service.type}}
  ports:
    - port: {{ .Values.techTalksProducer.service.port}}
      targetPort: {{ .Values.techTalksProducer.service.targetPort}}
      name: http-port
      protocol: TCP
  selector:
    {{- include "techtalks.producerLabels" . | nindent 4 }}  
