apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: techtalks-producer-api
  description: Tech Talks Producer api
  annotations:
    backstage.io/kubernetes-id: techtalks-producer-api
    sonarqube.org/project-key: nileshgule-github/NileshGule_cloud-native-ninja
  tags:
    - go
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
    - url: https://metrics.example-org.com
      title: metrics
      icon: analytics
      type: metrics-dashboard
    - url: https://logs.example-org.com
      title: logs
      icon: assignment
      type: logs-dashboard  
spec:
  type: service
  lifecycle: developement
  owner: users-team
  system: public-websites