name: cloud-native-ninja-techtalks-consumer-ci-cd
"on":
    push:
        branches:
            - main
        paths:
            - "src/go/consumer/**"
            
    workflow_dispatch: {}
env:
    ACR_RESOURCE_GROUP: acrResourceGroup
    AZURE_CONTAINER_REGISTRY: ngAcrRegistry
    CHART_OVERRIDE_PATH: ./techtalks-helm-chart/techtalk/values.yaml
    CHART_OVERRIDES: techTalksConsumer.image.repository=ngacrregistry.azurecr.io/techtalksconsumer,techTalksConsumer.image.tag=${{ github.sha }}
    CHART_PATH: ./techtalks-helm-chart/techtalk
    CLUSTER_NAME: azure-singapore-cluster
    CLUSTER_RESOURCE_GROUP: demo-azure-singapore-rg
    
jobs:
    buildImage:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
              name: Azure login
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            # - name: Build and push image to ACR
            #   run: az acr build --image ${{ env.CONTAINER_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.ACR_RESOURCE_GROUP }} -f ./docker-compose-go-acr.yml ./
            - name: Login to ACR
              run: az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }} 
            - name: Build the Docker image
              run: docker compose -f ./docker-compose-go-acr-ci.yml build techtalks.consumer
              env:
                IMAGE_TAG: ${{ github.sha }}
            - name: Push the Docker image
              run: docker compose -f ./docker-compose-go-acr-ci.yml push techtalks.consumer
              env:
                IMAGE_TAG: ${{ github.sha }}
    deploy:
        permissions:
            actions: read
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        needs:
            - buildImage
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
              name: Azure login
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            - uses: azure/use-kubelogin@v1
              name: Set up kubelogin for non-interactive login
              with:
                kubelogin-version: v0.0.25
            - uses: azure/aks-set-context@v3
              name: Get K8s context
              with:
                admin: "false"
                cluster-name: ${{ env.CLUSTER_NAME }}
                resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
                use-kubelogin: "true"
            - name: Deploy application
              run: helm upgrade --wait -i -f ${{ env.CHART_OVERRIDE_PATH }} --set ${{ env.CHART_OVERRIDES }} automated-deployment ${{ env.CHART_PATH }}
